// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvqrAUQGexKreTe2fi52nePOV2g5Am_ac',
    appId: '1:844469990124:web:f86cbfaaa09860a86e6bc9',
    messagingSenderId: '844469990124',
    projectId: 'goldfinche-ed986',
    authDomain: 'goldfinche-ed986.firebaseapp.com',
    storageBucket: 'goldfinche-ed986.firebasestorage.app',
    measurementId: 'G-880Z1X1PVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUAvcy9A5tiSFMWNb9uNpomMagDTUz8EU',
    appId: '1:844469990124:android:4dd9abc3d006b1c06e6bc9',
    messagingSenderId: '844469990124',
    projectId: 'goldfinche-ed986',
    storageBucket: 'goldfinche-ed986.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8hrTyF890YF_TfRH8-I2m41LYOx5fjvQ',
    appId: '1:844469990124:ios:e569ac6db2663cb26e6bc9',
    messagingSenderId: '844469990124',
    projectId: 'goldfinche-ed986',
    storageBucket: 'goldfinche-ed986.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
